### ISSUE TITLE
Getting started question

### ISSUE THREAD

**Issue by mmoore99** [Nothing-Works/inertia-aspnetcore#1]
```
@using InertiaAdapter
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inertia</title>
  </head>
  <body>
    @Inertia.Html(Model)

    <!-- reference your js file. -->
    <script src="/js/app.js"></script>
  </body>
</html>
```

What should `Model` contain in the code shown above?

I am also having trouble getting the client side code specified in the inertia docs to compile (see below). Do you possibly have a small example app that you could share showing how to get this going with Vue?

```
import { InertiaApp } from '@inertiajs/inertia-vue'
import Vue from 'vue'

Vue.use(InertiaApp)

const app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => require(`./Pages/${name}`).default,
    },
  }),
}).$mount(app)
```

**Comment by Nothing-Works** [comment]
@mmoore99 `Model` is supposed to contain three parts
```csharp
        public object? Controller { get; set; } //what you returned from controller.
        public object? Share { get; set; } //what you want to share from the global object, like auth etc.
        public object? With { get; set; } //what you put in the session.
```
Sorry, I do not have any example, I am planning to make some maybe next week. Do you have any errors in the console? or what's the current behaviour?

**Comment by mmoore99** [comment]
When I run "vue-cli-service build" to build the javascript I get the following error

```
Building for development...

 ERROR  Failed to compile with 1 errors                                                                                              1:18:22 PM

This relative module was not found:

* ./Pages in ./src/pages/home/index/index.js
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-app@0.1.0 dev: `vue-cli-service build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client-app@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mike\AppData\Roaming\npm-cache\_logs\2020-03-02T21_18_22_421Z-debug.log
```
index.js contains:

```
import Vue from "vue"
import { InertiaApp } from "@inertiajs/inertia-vue"

Vue.use(InertiaApp);

const app = document.getElementById("app");

new Vue({
    render: h => h(InertiaApp, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name => require(`./Pages/${name}`).default
            //resolveComponent: name => import(`./Pages/${name}`).then(module => module.default)
        }
    })
}).$mount(app);
```

**Comment by Nothing-Works** [comment]
@mmoore99 so as you provided this is the problem.
```javascript
This relative module was not found:

* ./Pages in ./src/pages/home/index/index.js
```
and I will close this as this is not really related to aspnetcore-adapter

**Comment by mmoore99** [comment]
> @mmoore99 `Model` is supposed to contain three parts
> 
> ```cs
>         public object? Controller { get; set; } //what you returned from controller.
>         public object? Share { get; set; } //what you want to share from the global object, like auth etc.
>         public object? With { get; set; } //what you put in the session.
> ```

I got this working, but in order to do so `Model` needs to contain a full `Page` object as Inertia has to be told what component to use on startup.

**Comment by Nothing-Works** [comment]
@mmoore99 yes, you are right.

this is the `Model`.
```csharp
        public string? Component { get; set; }
        public string? Version { get; set; }
        public string? Url { get; set; }
        public Props? Props { get; set; }
```

**Comment by mmoore99** [comment]
Thanks for developing this adapter and making it available. I have been
wanting to check out InertiaJs and this makes it feasible with dotnet.

**Comment by Nothing-Works** [comment]
@mmoore99 this repo still needs to be polished, I do not have much time atm, but I will definitely come back and add more examples in one or two weeks.

**Comment by jawa-the-hutt** [comment]
@mmoore99 Would you happen to have a basic example repo using Vue that you could share?

**Comment by mmoore99** [comment]
@jawa-the-hutt [here](https://github.com/mmoore99/InertiaJsTest) is a link to a repository that I have been hacking on to test inertia.js. It is really not in a form to share and it has some stuff in it that is not going to obvious what is going on. Also, I made some mods to the library created by @Nothing-Works .

In any case take a look if you would like.
