### ISSUE TITLE
[Question] Project still alive

### ISSUE THREAD

**Issue by ThaDaVos** [Nothing-Works/inertia-aspnetcore#2]
As the title says, is the project still alive? Looking at the master branch, the last commit was six months ago

**Comment by Nothing-Works** [comment]
@ThaDaVos yes, it's still alive, I am planning to get back to it soon.

**Comment by ashokgelal** [comment]
I'm glad to hear that this project isn't dead, I was worried. Is there anything missing that you plan to fix or add?  I've written [an InertiaJS adapter](https://github.com/alpas/inertia) myself for a [Kotlin backend framework](https://github.com/alpas/alpas) but for work I have to now use ASP .NET Core. I would love to contribute.

**Comment by Nothing-Works** [comment]
@ashokgelal oh, that's really nice to hear.

1. for things to add/fix: I need to make a todo list, sorry it's ready yet.
2. Another thing I am not very happy about is that the overall structure of the adapter, I need to do some refactoring.
3. Then maybe some example repos as someone has getting started problems.

**Comment by Wulfheart** [comment]
@Nothing-Works What about the todo-list and the refactoring? 😄

**Comment by Nothing-Works** [comment]
@Wulfheart Sorry about no update, all I can say is that it's still on my list and high priority.
