### ISSUE TITLE
JSON cuts off in the data-page attribute

### ISSUE THREAD

**Issue by zevenbergm** [Nothing-Works/inertia-aspnetcore#3]
First of all, thanks for this awesome piece of work. I face a small issue, the JSON cuts off in the data-page attribute:

![image](https://user-images.githubusercontent.com/16295670/83798100-01025980-a6a4-11ea-9e93-03adbbd0e3e6.png)

Do you have an idea how I can solve this?

**Comment by Nothing-Works** [comment]
what did you pass from the controller? @zevenbergm

**Comment by zevenbergm** [comment]
I pass an anonymous object from the server.

**Comment by subhananam** [comment]
Hi,, first of all,, thank you for making this adaptor,, i really appreciate that,, i'm recently learn inertia.js and want to implement this to my ASP.NET Core project,, is there a sample project i can learn?

**Comment by Wulfheart** [comment]
@subhananam Take a llok at this PR #4.

**Comment by imrandyk** [comment]
@Wulfheart and @subhananam the example has been moved to it's own [repo](https://github.com/imrandyk/inertia-aspnetcore-react-example) and has been submitted in PR [#5](https://github.com/Nothing-Works/inertia-aspnetcore/pull/5)
